package com.sanket.tools.passwordmanager.data.crypto

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi

/**
 * Android actual: wraps the vault key with a hardware-backed
 * key from the Android Keystore, then stores the wrapped bytes
 * in SharedPreferences.
 *
 * Flow:
 *   1. Get-or-create an AES-256-GCM key in Android Keystore (KEY_ALIAS)
 *   2. Use it to encrypt the vault key → store encrypted bytes in SharedPrefs
 *   3. On load: unwrap encrypted bytes using the same Keystore key
 *
 * The raw vault key NEVER touches disk — only the Keystore-wrapped version does.
 */
@OptIn(ExperimentalEncodingApi::class)
actual class KeystoreManager(private val context: Context) {

    private val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

    // ─────────────────────────────────────────────────────────────────────
    // PUBLIC API
    // ─────────────────────────────────────────────────────────────────────

    actual fun saveVaultKey(vaultKey: ByteArray) {
        val wrappingKey = getOrCreateWrappingKey()

        val cipher = Cipher.getInstance(AES_GCM_TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, wrappingKey)

        val wrappedKey = cipher.doFinal(vaultKey)
        val iv = cipher.iv  // generated by cipher on ENCRYPT_MODE

        prefs.edit()
            .putString(PREF_WRAPPED_KEY, Base64.encode(wrappedKey))
            .putString(PREF_IV, Base64.encode(iv))
            .apply()
    }

    actual fun loadVaultKey(): ByteArray? {
        val wrappedStr = prefs.getString(PREF_WRAPPED_KEY, null) ?: return null
        val ivStr = prefs.getString(PREF_IV, null) ?: return null

        val wrappedKey = Base64.decode(wrappedStr)
        val iv = Base64.decode(ivStr)

        val wrappingKey = getOrCreateWrappingKey()
        val cipher = Cipher.getInstance(AES_GCM_TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, wrappingKey, GCMParameterSpec(TAG_BITS, iv))

        return cipher.doFinal(wrappedKey)
    }

    actual fun clearVaultKey() {
        prefs.edit()
            .remove(PREF_WRAPPED_KEY)
            .remove(PREF_IV)
            .apply()
    }

    // ─────────────────────────────────────────────────────────────────────
    // PRIVATE HELPERS
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Get the hardware-backed wrapping key from Android Keystore.
     * Creates it the first time — subsequent calls just load it.
     */
    private fun getOrCreateWrappingKey(): SecretKey {
        val keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }

        if (!keyStore.containsAlias(KEY_ALIAS)) {
            val keyGen = KeyGenerator.getInstance(
                KeyProperties.KEY_ALGORITHM_AES,
                KEYSTORE_PROVIDER
            )
            keyGen.init(
                KeyGenParameterSpec.Builder(
                    KEY_ALIAS,
                    KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
                )
                    .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                    .setKeySize(256)
                    .build()
            )
            keyGen.generateKey()
        }

        val entry = keyStore.getEntry(KEY_ALIAS, null) as KeyStore.SecretKeyEntry
        return entry.secretKey
    }

    companion object {
        private const val KEYSTORE_PROVIDER   = "AndroidKeyStore"
        private const val KEY_ALIAS           = "pm_vault_wrap_key"
        private const val PREFS_NAME          = "pm_secure_prefs"
        private const val PREF_WRAPPED_KEY    = "wrapped_vault_key"
        private const val PREF_IV             = "wrap_iv"
        private const val AES_GCM_TRANSFORMATION = "AES/GCM/NoPadding"
        private const val TAG_BITS            = 128
    }
}
